name       : cef-minimal
version    : 112.0.5615.165
release    : 12
source     :
    - https://cef-builds.spotifycdn.com/cef_binary_112.3.0+gb09c4ca+chromium-112.0.5615.165_linux64_minimal.tar.bz2 : 498afff6dc0ea5e9aa60ba7a7bb11fa5258fbe40991095ebddace0cadabf710b
license    : BSD-3-Clause
component  : programming.library
summary    : Minimal build of Chromium Embedded Framework
description: |
    Minimal build of Chromium Embedded Framework
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - cups-devel
patterns   :
    - devel :
        - /usr/share/**/CMake*
        - /usr/share/**/Make*
        - /usr/share/**/cmake*
        - /usr/share/**/include*
        - /usr/share/**/*.h
        - /usr/share/**/*.cc
        - /usr/share/**/*.cmake
        - /usr/share/cef-minimal/libcef_dll
        - /usr/share/cef-minimal/libcef_dll_wrapper/CMakeFiles
        - /usr/share/cef-minimal/libcef_dll_wrapper/Makefile
        - /usr/share/cef-minimal/libcef_dll_wrapper/cmake_install.cmake
setup      : |
    rm -rf $workdir/tests
    %cmake .
build      : |
    make clean
    %make libcef_dll_wrapper
install    : |
    install -dm00644 $installdir/usr/share/cef-minimal
    mv $workdir/* $installdir/usr/share/cef-minimal/
    ln -s /usr/share/cef-minimal/libcef_dll_wrapper/libcef_dll_wrapper.a $installdir/usr/share/cef-minimal/Release/libcef_dll_wrapper.a
