name       : cef-minimal
version    : 95.0.4638.69
release    : 6
source     :
    - https://cef-builds.spotifycdn.com/cef_binary_95.7.18+g0d6005e+chromium-95.0.4638.69_linux64_minimal.tar.bz2 : cf865f4d2c9498e9618633cd099f637aea368fa51c44bb47ce0de55f17500133
license    : BSD-3-Clause
component  : programming.library
summary    : Minimal build of Chromium Embedded Framework
description: |
    Minimal build of Chromium Embedded Framework
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - cups-devel
patterns   :
    - devel :
        - /usr/share/**/CMake*
        - /usr/share/**/Make*
        - /usr/share/**/cmake*
        - /usr/share/**/include*
        - /usr/share/**/*.h
        - /usr/share/**/*.cc
        - /usr/share/**/*.cmake
        - /usr/share/cef-minimal/libcef_dll
        - /usr/share/cef-minimal/libcef_dll_wrapper/CMakeFiles
        - /usr/share/cef-minimal/libcef_dll_wrapper/Makefile
        - /usr/share/cef-minimal/libcef_dll_wrapper/cmake_install.cmake
setup      : |
    %cmake .
build      : |
    make clean
    %make libcef_dll_wrapper
install    : |
    install -dm00644 $installdir/usr/share/cef-minimal
    mv $workdir/* $installdir/usr/share/cef-minimal/
    ln -s /usr/share/cef-minimal/libcef_dll_wrapper/libcef_dll_wrapper.a $installdir/usr/share/cef-minimal/Release/libcef_dll_wrapper.a
