name       : cef-minimal
version    : 88.0.4324.150
release    : 4
source     :
    - https://cef-builds.spotifycdn.com/cef_binary_88.2.4+gf3c4ca9+chromium-88.0.4324.150_linux64_minimal.tar.bz2 : f341b128963dd3238787a7a28f26ff4e7c2256456013bf4cd79a70dd6e386c5a
license    : BSD-3-Clause
component  : programming.library
summary    : Minimal build of Chromium Embedded Framework
description: |
    Minimal build of Chromium Embedded Framework
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - cups-devel
patterns   :
    - devel:
      - /usr/share/**/CMake*
      - /usr/share/**/Make*
      - /usr/share/**/cmake*
      - /usr/share/**/include*
      - /usr/share/**/*.h
      - /usr/share/**/*.cc
      - /usr/share/**/*.cmake
      - /usr/share/cef-minimal/libcef_dll
      - /usr/share/cef-minimal/libcef_dll_wrapper/CMakeFiles
      - /usr/share/cef-minimal/libcef_dll_wrapper/Makefile
      - /usr/share/cef-minimal/libcef_dll_wrapper/cmake_install.cmake
setup      : |
    %cmake .
build      : |
    make clean
    %make libcef_dll_wrapper
install    : |
    install -dm00644 $installdir/usr/share/cef-minimal
    mv $workdir/* $installdir/usr/share/cef-minimal/
    ln -s /usr/share/cef-minimal/libcef_dll_wrapper/libcef_dll_wrapper.a $installdir/usr/share/cef-minimal/Release/libcef_dll_wrapper.a
